python ./dvbs2_18_dynamic_range_awng_min_level.py
python ./dvbs2_18_dynamic_range_awng_min_level.py
python ./dvbs2_18_dynamic_range_awng_min_level.py
python ./dvbs2_18_dynamic_range_awng_min_level.py
python ./dvbs2_18_dynamic_range_awng_min_level.py
python ./dvbs2_18_dynamic_range_awng_min_level.py
python ./dvbs2_18_dynamic_range_awng_min_level.py
python ./dvbs2_18_dynamic_range_awng_min_level.py
python ./dvbs2_18_dynamic_range_awng_max_level.py
python ./dvbs2_19_symbol_rate_step.py
python ./dvbs2_22_phase_distortion_test.py
python ./dvbs2_23_amplitude_distortion_test.py
python ./dvbs2_24_symbol_err_rate.py
python ./dvbs2_25_signal_acquisition_frequency_range.py
python ./dvbs2_26_signal_tracking_frequency_range.py