python ./dvbc_2_channel_bandwidth.py
python ./dvbc_3_cn_test.py
python ./dvbc_4_symbol_rate.py
python ./dvbc_5_IQ_inverted.py
python ./dvbc_7_analogue_adjacent_carrier_interference_N+1.py
python ./dvbc_7_analogue_adjacent_carrier_interference_N-1.py
python ./dvbc_8_symbol_error_rate.py
python ./dvbc_9_frequency_error_rate.py
python ./dvbc_10_frequency_capture_range.py
python ./dvbc_1_dynamic_range_awng_max_level.py
python ./dvbc_1_dynamic_range_awng_min_level.py
python ./dvbc_2_channel_bandwidth.py
python ./dvbc_3_cn_test.py
python ./dvbc_4_symbol_rate.py
python ./dvbc_5_IQ_inverted.py
python ./dvbc_7_analogue_adjacent_carrier_interference_N+1.py
python ./dvbc_7_analogue_adjacent_carrier_interference_N-1.py
python ./dvbc_8_symbol_error_rate.py
python ./dvbc_9_frequency_error_rate.py
python ./dvbc_10_frequency_capture_range.py
python ./dvbc_1_dynamic_range_awng_max_level.py
python ./dvbc_1_dynamic_range_awng_min_level.py
