python ./dvbt_4_centre_frequencies.py
python ./dvbt_5_frequency_offset.py
python ./dvbt_6_signal_bandwidth.py
python ./dvbt_7_modes.py
python ./dvbt_13_verification_signal_strength_indicator_ssi.py
python ./dvbt_14_verification_signal_quality_indicator_sqi.py
python ./dvbt_15_changes_modulation_parameters.py
python ./dvbt_19_performance_gaussian_channel.py
python ./dvbt_20_performance_0db_echo_channel.py
python ./dvbt_21_receiver_signal_input__min_level.py
python ./dvbt_22_minimun_signal_level_0db.py
python ./dvbt_24_receiver_signal_maximum_level.py
python ./dvbt_25_analogue_singnal_other_channel.py
python ./dvbt_28_co_channek_interference_analogue.py
python ./dvbt_30_synchronisation_varying_echo.py
python ./dvbt_31_performance_SFN_more_than_one.py
python ./dvbt_32_performance_SFN_inside_guard.py
python ./dvbt_33_performance_SFN_outside_guard.py