python ./dvbt2_59_receiver_signal_input__min_level.py
python ./dvbt2_59_receiver_signal_input__min_level.py
python ./dvbt2_59_receiver_signal_input__min_level.py
python ./dvbt2_59_receiver_signal_input__min_level.py
python ./dvbt2_59_receiver_signal_input__min_level.py
python ./dvbt2_57_performance_gaussian_channel.py
python ./dvbt2_57_performance_gaussian_channel.py
python ./dvbt2_57_performance_gaussian_channel.py
python ./dvbt2_57_performance_gaussian_channel.py
python ./dvbt2_57_performance_gaussian_channel.py
python ./dvbt2_34_centre_frequencies.py
python ./dvbt2_35_frequency_offset.py
python ./dvbt2_36_signal_bandwidths.py
python ./dvbt2_37_modes.py
python ./dvbt2_37_modes_supplument_1_rotation.py
python ./dvbt2_37_modes_supplument_2_papr.py
python ./dvbt2_37_modes_supplument_3_fft_pilot.py
python ./dvbt2_44_normal_mode.py
python ./dvbt2_51_verification_signal_strength_indicator_ssi.py
python ./dvbt2_52_verification_signal_quality_indicator_sqi.py
python ./dvbt2_53_changes_modulation_parameters.py
python ./dvbt2_53_changes_modulation_supplement_1_extension.py
python ./dvbt2_53_changes_modulation_supplement_2_PARP.py
python ./dvbt2_54_time_interleaving.py
python ./dvbt2_58_performance_0db_echo_channel.py
python ./dvbt2_60_minimum_level_0db_echo_channel.py
python ./dvbt2_62_maximum_signal_levels.py
python ./dvbt2_65_co_channel_interference.py
python ./dvbt2_67_synchronisation_varying_echo.py
python ./dvbt2_68_performance_in_SFN_echo.py
python ./dvbt2_69_performance_in_SFN_inside_guard.py
python ./dvbt2_70_performance_in_frequency_outside.py
python ./dvbt2_59_receiver_signal_input__min_level.py
python ./dvbt2_57_performance_gaussian_channel.py
python ./dvbt2_34_centre_frequencies.py
python ./dvbt2_35_frequency_offset.py
python ./dvbt2_36_signal_bandwidths.py
python ./dvbt2_37_modes.py
python ./dvbt2_37_modes_supplument_1_rotation.py
python ./dvbt2_37_modes_supplument_2_papr.py
python ./dvbt2_37_modes_supplument_3_fft_pilot.py
python ./dvbt2_44_normal_mode.py
python ./dvbt2_51_verification_signal_strength_indicator_ssi.py
python ./dvbt2_52_verification_signal_quality_indicator_sqi.py
python ./dvbt2_53_changes_modulation_parameters.py
python ./dvbt2_53_changes_modulation_supplement_1_extension.py
python ./dvbt2_53_changes_modulation_supplement_2_PARP.py
python ./dvbt2_54_time_interleaving.py
python ./dvbt2_58_performance_0db_echo_channel.py
python ./dvbt2_60_minimum_level_0db_echo_channel.py
python ./dvbt2_62_maximum_signal_levels.py
python ./dvbt2_65_co_channel_interference.py
python ./dvbt2_67_synchronisation_varying_echo.py
python ./dvbt2_68_performance_in_SFN_echo.py
python ./dvbt2_69_performance_in_SFN_inside_guard.py
python ./dvbt2_70_performance_in_frequency_outside.py